
export const SdSamplers = [
    {label: 'Euler a', value: 'Euler a'},
    {label: 'Euler', value: 'Euler'},
    {label: 'DPM++ 2M Karras', value: 'DPM++ 2M Karras'},
    {label: 'DPM++ SDE Karras', value: 'DPM++ SDE Karras'},
    {label: 'DPM++ 2M SDE Exponential', value: 'DPM++ 2M SDE Exponential'},
    {label: 'DPM++ 2M SDE Karras', value: 'DPM++ 2M SDE Karras'},
    {label: 'LMS', value: 'LMS'},
    {label: 'Heun', value: 'Heun'},
    {label: 'DPM2', value: 'DPM2'},
    {label: 'DPM2 a', value: 'DPM2 a'},
    {label: 'DPM++ 2S a', value: 'DPM++ 2S a'},
    {label: 'DPM++ 2M', value: 'DPM++ 2M'},
    {label: 'DPM++ SDE', value: 'DPM++ SDE'},
    {label: 'DPM++ 2M SDE', value: 'DPM++ 2M SDE'},
    {label: 'DPM++ 2M SDE Heun', value: 'DPM++ 2M SDE Heun'},
    {label: 'DPM++ 2M SDE Heun Karras', value: 'DPM++ 2M SDE Heun Karras'},
    {label: 'DPM++ 2M SDE Heun Exponential', value: 'DPM++ 2M SDE Heun Exponential'},
    {label: 'DPM++ 3M SDE', value: 'DPM++ 3M SDE'},
    {label: 'DPM++ 3M SDE Karras', value: 'DPM++ 3M SDE Karras'},
    {label: 'DPM++ 3M SDE Exponential', value: 'DPM++ 3M SDE Exponential'},
    {label: 'DPM fast', value: 'DPM fast'},
    {label: 'DPM adaptive', value: 'DPM adaptive'},
    {label: 'LMS Karras', value: 'LMS Karras'},
    {label: 'DPM2 Karras', value: 'DPM2 Karras'},
    {label: 'DPM2 a Karras', value: 'DPM2 a Karras'},
    {label: 'DPM++ 2S a Karras', value: 'DPM++ 2S a Karras'},
    {label: 'Restart', value: 'Restart'},
    {label: 'DDIM', value: 'DDIM'},
    {label: 'PLMS', value: 'PLMS'},
    {label: 'UniPC', value: 'UniPC'},
    {label: 'LCM', value: 'LCM'},
]


export const SdHiresUpScalers = [
    {label: 'Latent', value: 'Latent'},
    {label: 'Latent (antialiased)', value: 'Latent (antialiased)'},
    {label: 'Latent (bicubic)', value: 'Latent (bicubic)'},
    {label: 'Latent (bicubic antialiased)', value: 'Latent (bicubic antialiased)'},
    {label: 'Latent (nearest)', value: 'Latent (nearest)'},
    {label: 'Latent (nearest-exact)', value: 'Latent (nearest-exact)'},
    {label: 'None', value: 'None'},
    {label: 'Lanczos', value: 'Lanczos'},
    {label: 'Nearest', value: 'Nearest'},
    {label: 'ESRGAN_4x', value: 'ESRGAN_4x'},
    {label: 'LDSR', value: 'LDSR'},
    {label: 'R-ESRGAN 4x+', value: 'R-ESRGAN 4x+'},
    {label: 'R-ESRGAN 4x+ Anime6B', value: 'R-ESRGAN 4x+ Anime6B'},
    {label: 'ScuNET GAN', value: 'ScuNET GAN'},
    {label: 'ScuNET PSNR', value: 'ScuNET PSNR'},
    {label: 'SwinIR 4x', value: 'SwinIR 4x'},
]